### ISSUE TITLE
reuse-client has no effect

### ISSUE THREAD

**Issue by dmichulke** [gerritjvv/clj-tcp#2]
From looking at the source code, reuse-client is an argument that is never read

**Comment by gerritjvv** [comment]
hi, thanks for reporting this. 
I'll cleanup the options. 

Seems like the library failed for you during some operations, can you give me an example (code ) of what you did so I may replicate and fix the issue?

**Comment by gerritjvv** [comment]
I've updated the README and removed the un-used arguments.
